# Exported from Render on 2024-04-07T01:38:38Z
services:
  - type: pserv
    name: mongodb
    runtime: docker
    repo: https://github.com/render-examples/mongodb
    branch: main
    plan: starter
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10
    autoDeploy: false

  - type: web
    name: artisan-connect
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    plan: starter
    region: oregon
    envVars:
      - key: MONGODB_URI
        fromService:
          name: mongodb
          type: addon
    healthCheckPath: /health

version: "1"
